-- MySQL Script generated by MySQL Workbench
-- Tue Mar 10 19:49:59 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

CREATE DATABASE IF NOT EXISTS restaurante-app;
USE restaurante-app;

-- =========================
-- TABLA ROL EMPLEADO
-- =========================
CREATE TABLE tblRolEmpleado (
    idRol INT AUTO_INCREMENT PRIMARY KEY,
    nombreRol VARCHAR(45) NOT NULL,
    nivelAutorizacion INT NOT NULL,
    porcentajeDescuentoPermitido DECIMAL(5,2) DEFAULT 0
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4;

-- =========================
-- TABLA SUCURSAL
-- =========================
CREATE TABLE tblSucursal (
    idSucursal INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100),
    direccion VARCHAR(150),
    telefono VARCHAR(20),
    horarioAtencion VARCHAR(50)
);

-- =========================
-- TABLA MESA
-- =========================
CREATE TABLE tblMesa (
    idMesa INT AUTO_INCREMENT PRIMARY KEY,
    numero INT,
    capacidad INT,
    estado VARCHAR(20),
    ubicacion VARCHAR(50),
    idSucursal INT,
    FOREIGN KEY (idSucursal) REFERENCES tblSucursal(idSucursal)
);

-- =========================
-- TABLA EMPLEADO
-- =========================
CREATE TABLE tblEmpleado (
    idEmpleado INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100),
    identificacion VARCHAR(50),
    estado VARCHAR(20),
    fechaIngreso DATE,
    idSucursal INT,
    idRol INT,
    FOREIGN KEY (idSucursal) REFERENCES tblSucursal(idSucursal),
    FOREIGN KEY (idRol) REFERENCES tblRolEmpleado(idRol)
);

-- =========================
-- TABLA TURNOS
-- =========================
CREATE TABLE tblTurnos (
    idTurno INT AUTO_INCREMENT PRIMARY KEY,
    fecha DATE,
    horaInicio TIME,
    horaFin TIME,
    idEmpleado INT,
    FOREIGN KEY (idEmpleado) REFERENCES tblEmpleado(idEmpleado)
);

-- =========================
-- TABLA ASIGNACION MESA
-- =========================
CREATE TABLE tblAsignacionMesa (
    idAsignacion INT AUTO_INCREMENT PRIMARY KEY,
    fecha DATE,
    horaInicio TIME,
    horaFin TIME,
    idMesa INT,
    idEmpleado INT,
    idTurno INT,
    FOREIGN KEY (idMesa) REFERENCES tblMesa(idMesa),
    FOREIGN KEY (idEmpleado) REFERENCES tblEmpleado(idEmpleado),
    FOREIGN KEY (idTurno) REFERENCES tblTurnos(idTurno)
);

-- =========================
-- TABLA PEDIDO
-- =========================
CREATE TABLE tblPedido (
    idPedido INT AUTO_INCREMENT PRIMARY KEY,
    fechaHora DATETIME,
    estado VARCHAR(20),
    observacionesCliente VARCHAR(200),
    idEmpleado INT,
    idMesa INT,
    FOREIGN KEY (idEmpleado) REFERENCES tblEmpleado(idEmpleado),
    FOREIGN KEY (idMesa) REFERENCES tblMesa(idMesa)
);

-- =========================
-- TABLA CAJA
-- =========================
CREATE TABLE tblCaja (
    idCaja INT AUTO_INCREMENT PRIMARY KEY,
    fechaApertura DATETIME,
    fechaCierre DATETIME,
    montoInicial DECIMAL(10,2),
    montoFinal DECIMAL(10,2),
    idSucursal INT,
    FOREIGN KEY (idSucursal) REFERENCES tblSucursal(idSucursal)
);

-- =========================
-- TABLA FACTURA
-- =========================
CREATE TABLE tblFactura (
    idFactura INT AUTO_INCREMENT PRIMARY KEY,
    subtotal DECIMAL(10,2),
    impuesto DECIMAL(10,2),
    propina DECIMAL(10,2),
    total DECIMAL(10,2),
    fechaHoraCierre DATETIME,
    idPedido INT,
    idCaja INT,
    FOREIGN KEY (idPedido) REFERENCES tblPedido(idPedido),
    FOREIGN KEY (idCaja) REFERENCES tblCaja(idCaja)
);

-- =========================
-- TABLA CATEGORIA PRODUCTO
-- =========================
CREATE TABLE tblCategoriaProducto (
    idCategoria INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50)
);

-- =========================
-- TABLA PRODUCTO
-- =========================
CREATE TABLE tblProducto (
    idProducto INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100),
    descripcion VARCHAR(200),
    precioVenta DECIMAL(10,2),
    costo DECIMAL(10,2),
    disponible BOOLEAN,
    informacionNutricional VARCHAR(200),
    alergenos VARCHAR(200),
    tiempoPreparacion INT,
    idCategoria INT,
    FOREIGN KEY (idCategoria) REFERENCES tblCategoriaProducto(idCategoria)
);

-- =========================
-- TABLA INGREDIENTE
-- =========================
CREATE TABLE tblIngrediente (
    idIngrediente INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100),
    unidadMedida VARCHAR(20),
    stockActual DECIMAL(10,2),
    stockMinimo DECIMAL(10,2)
);

-- =========================
-- TABLA RECETA
-- =========================
CREATE TABLE tblReceta (
    idProducto INT,
    idIngrediente INT,
    cantidad DECIMAL(10,2),
    PRIMARY KEY (idProducto,idIngrediente),
    FOREIGN KEY (idProducto) REFERENCES tblProducto(idProducto),
    FOREIGN KEY (idIngrediente) REFERENCES tblIngrediente(idIngrediente)
);

-- =========================
-- DETALLE PEDIDO
-- =========================
CREATE TABLE tblDetallePedido (
    idDetalle INT AUTO_INCREMENT PRIMARY KEY,
    idPedido INT,
    idProducto INT,
    cantidad INT,
    precioUnitario DECIMAL(10,2),
    notaEspecial VARCHAR(200),
    FOREIGN KEY (idPedido) REFERENCES tblPedido(idPedido),
    FOREIGN KEY (idProducto) REFERENCES tblProducto(idProducto)
);

-- =========================
-- TABLA PAGO
-- =========================
CREATE TABLE tblPago (
    idPago INT AUTO_INCREMENT PRIMARY KEY,
    monto DECIMAL(10,2),
    metodoPago VARCHAR(30),
    fechaHora DATETIME,
    idFactura INT,
    FOREIGN KEY (idFactura) REFERENCES tblFactura(idFactura)
);

-- =========================
-- EVALUACION DESEMPEÑO
-- =========================
CREATE TABLE tblEvaluacionDesempeno (
    idEvaluacion INT AUTO_INCREMENT PRIMARY KEY,
    fecha DATE,
    calificacion INT,
    observaciones VARCHAR(200),
    idEmpleado INT,
    FOREIGN KEY (idEmpleado) REFERENCES tblEmpleado(idEmpleado)
);